/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AyTammDataInterface extends ethers.utils.Interface {
  functions: {
    "FCPaddress()": FunctionFragment;
    "SlippageConstant()": FunctionFragment;
    "YTtoLmultiplier()": FunctionFragment;
    "ZCBammAddress()": FunctionFragment;
    "lastRecalibration()": FunctionFragment;
    "maturity()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "FCPaddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SlippageConstant",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "YTtoLmultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ZCBammAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastRecalibration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maturity", values?: undefined): string;

  decodeFunctionResult(functionFragment: "FCPaddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SlippageConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "YTtoLmultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ZCBammAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRecalibration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maturity", data: BytesLike): Result;

  events: {};
}

export class AyTammData extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AyTammDataInterface;

  functions: {
    FCPaddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "FCPaddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    SlippageConstant(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "SlippageConstant()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    YTtoLmultiplier(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "YTtoLmultiplier()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    ZCBammAddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "ZCBammAddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    lastRecalibration(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "lastRecalibration()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    maturity(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "maturity()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  FCPaddress(overrides?: CallOverrides): Promise<string>;

  "FCPaddress()"(overrides?: CallOverrides): Promise<string>;

  SlippageConstant(overrides?: CallOverrides): Promise<BigNumber>;

  "SlippageConstant()"(overrides?: CallOverrides): Promise<BigNumber>;

  YTtoLmultiplier(overrides?: CallOverrides): Promise<BigNumber>;

  "YTtoLmultiplier()"(overrides?: CallOverrides): Promise<BigNumber>;

  ZCBammAddress(overrides?: CallOverrides): Promise<string>;

  "ZCBammAddress()"(overrides?: CallOverrides): Promise<string>;

  lastRecalibration(overrides?: CallOverrides): Promise<BigNumber>;

  "lastRecalibration()"(overrides?: CallOverrides): Promise<BigNumber>;

  maturity(overrides?: CallOverrides): Promise<BigNumber>;

  "maturity()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    FCPaddress(overrides?: CallOverrides): Promise<string>;

    "FCPaddress()"(overrides?: CallOverrides): Promise<string>;

    SlippageConstant(overrides?: CallOverrides): Promise<BigNumber>;

    "SlippageConstant()"(overrides?: CallOverrides): Promise<BigNumber>;

    YTtoLmultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    "YTtoLmultiplier()"(overrides?: CallOverrides): Promise<BigNumber>;

    ZCBammAddress(overrides?: CallOverrides): Promise<string>;

    "ZCBammAddress()"(overrides?: CallOverrides): Promise<string>;

    lastRecalibration(overrides?: CallOverrides): Promise<BigNumber>;

    "lastRecalibration()"(overrides?: CallOverrides): Promise<BigNumber>;

    maturity(overrides?: CallOverrides): Promise<BigNumber>;

    "maturity()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    FCPaddress(overrides?: CallOverrides): Promise<BigNumber>;

    "FCPaddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    SlippageConstant(overrides?: CallOverrides): Promise<BigNumber>;

    "SlippageConstant()"(overrides?: CallOverrides): Promise<BigNumber>;

    YTtoLmultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    "YTtoLmultiplier()"(overrides?: CallOverrides): Promise<BigNumber>;

    ZCBammAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "ZCBammAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    lastRecalibration(overrides?: CallOverrides): Promise<BigNumber>;

    "lastRecalibration()"(overrides?: CallOverrides): Promise<BigNumber>;

    maturity(overrides?: CallOverrides): Promise<BigNumber>;

    "maturity()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    FCPaddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "FCPaddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SlippageConstant(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "SlippageConstant()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    YTtoLmultiplier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "YTtoLmultiplier()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ZCBammAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ZCBammAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastRecalibration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lastRecalibration()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maturity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maturity()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
