/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DbsfVaultFactoryDelegate4Interface extends ethers.utils.Interface {
  functions: {
    "auctionYTLiquidation(address,uint256,address,address,uint256,int256,uint256)": FunctionFragment;
    "bidOnYTLiquidation(uint256,uint256,uint256)": FunctionFragment;
    "claimYTLiquidation(uint256,address)": FunctionFragment;
    "instantYTLiquidation(address,uint256,address,address,uint256,uint256,int256,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "partialYTLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,int256,address)": FunctionFragment;
    "partialYTLiquidationSpecificOut(address,uint256,address,address,uint256,int256,uint256,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "auctionYTLiquidation",
    values: [
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bidOnYTLiquidation",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimYTLiquidation",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "instantYTLiquidation",
    values: [
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "partialYTLiquidationSpecificIn",
    values: [
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "partialYTLiquidationSpecificOut",
    values: [
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionYTLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidOnYTLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimYTLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "instantYTLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "partialYTLiquidationSpecificIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partialYTLiquidationSpecificOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {};
}

export class DbsfVaultFactoryDelegate4 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DbsfVaultFactoryDelegate4Interface;

  functions: {
    auctionYTLiquidation(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _bidYield: BigNumberish,
      _minBondRatio: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "auctionYTLiquidation(address,uint256,address,address,uint256,int256,uint256)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _bidYield: BigNumberish,
      _minBondRatio: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bidOnYTLiquidation(
      _index: BigNumberish,
      _bidYield: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bidOnYTLiquidation(uint256,uint256,uint256)"(
      _index: BigNumberish,
      _bidYield: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimYTLiquidation(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimYTLiquidation(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    instantYTLiquidation(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "instantYTLiquidation(address,uint256,address,address,uint256,uint256,int256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    partialYTLiquidationSpecificIn(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "partialYTLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,int256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    partialYTLiquidationSpecificOut(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _out: BigNumberish,
      _minBondOut: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "partialYTLiquidationSpecificOut(address,uint256,address,address,uint256,int256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _out: BigNumberish,
      _minBondOut: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  auctionYTLiquidation(
    _owner: string,
    _index: BigNumberish,
    _FCPborrowed: string,
    _FCPsupplied: string,
    _bidYield: BigNumberish,
    _minBondRatio: BigNumberish,
    _amtIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "auctionYTLiquidation(address,uint256,address,address,uint256,int256,uint256)"(
    _owner: string,
    _index: BigNumberish,
    _FCPborrowed: string,
    _FCPsupplied: string,
    _bidYield: BigNumberish,
    _minBondRatio: BigNumberish,
    _amtIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bidOnYTLiquidation(
    _index: BigNumberish,
    _bidYield: BigNumberish,
    _amtIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bidOnYTLiquidation(uint256,uint256,uint256)"(
    _index: BigNumberish,
    _bidYield: BigNumberish,
    _amtIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimYTLiquidation(
    _index: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimYTLiquidation(uint256,address)"(
    _index: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  instantYTLiquidation(
    _owner: string,
    _index: BigNumberish,
    _FCPborrowed: string,
    _FCPsupplied: string,
    _maxIn: BigNumberish,
    _minOut: BigNumberish,
    _minBondRatio: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "instantYTLiquidation(address,uint256,address,address,uint256,uint256,int256,address)"(
    _owner: string,
    _index: BigNumberish,
    _FCPborrowed: string,
    _FCPsupplied: string,
    _maxIn: BigNumberish,
    _minOut: BigNumberish,
    _minBondRatio: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  partialYTLiquidationSpecificIn(
    _owner: string,
    _index: BigNumberish,
    _FCPborrowed: string,
    _FCPsupplied: string,
    _in: BigNumberish,
    _minOut: BigNumberish,
    _minBondRatio: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "partialYTLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,int256,address)"(
    _owner: string,
    _index: BigNumberish,
    _FCPborrowed: string,
    _FCPsupplied: string,
    _in: BigNumberish,
    _minOut: BigNumberish,
    _minBondRatio: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  partialYTLiquidationSpecificOut(
    _owner: string,
    _index: BigNumberish,
    _FCPborrowed: string,
    _FCPsupplied: string,
    _out: BigNumberish,
    _minBondOut: BigNumberish,
    _maxIn: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "partialYTLiquidationSpecificOut(address,uint256,address,address,uint256,int256,uint256,address)"(
    _owner: string,
    _index: BigNumberish,
    _FCPborrowed: string,
    _FCPsupplied: string,
    _out: BigNumberish,
    _minBondOut: BigNumberish,
    _maxIn: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    auctionYTLiquidation(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _bidYield: BigNumberish,
      _minBondRatio: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "auctionYTLiquidation(address,uint256,address,address,uint256,int256,uint256)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _bidYield: BigNumberish,
      _minBondRatio: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    bidOnYTLiquidation(
      _index: BigNumberish,
      _bidYield: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "bidOnYTLiquidation(uint256,uint256,uint256)"(
      _index: BigNumberish,
      _bidYield: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimYTLiquidation(
      _index: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "claimYTLiquidation(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    instantYTLiquidation(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "instantYTLiquidation(address,uint256,address,address,uint256,uint256,int256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    partialYTLiquidationSpecificIn(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "partialYTLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,int256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    partialYTLiquidationSpecificOut(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _out: BigNumberish,
      _minBondOut: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "partialYTLiquidationSpecificOut(address,uint256,address,address,uint256,int256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _out: BigNumberish,
      _minBondOut: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    auctionYTLiquidation(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _bidYield: BigNumberish,
      _minBondRatio: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "auctionYTLiquidation(address,uint256,address,address,uint256,int256,uint256)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _bidYield: BigNumberish,
      _minBondRatio: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bidOnYTLiquidation(
      _index: BigNumberish,
      _bidYield: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bidOnYTLiquidation(uint256,uint256,uint256)"(
      _index: BigNumberish,
      _bidYield: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimYTLiquidation(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimYTLiquidation(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    instantYTLiquidation(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "instantYTLiquidation(address,uint256,address,address,uint256,uint256,int256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    partialYTLiquidationSpecificIn(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "partialYTLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,int256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    partialYTLiquidationSpecificOut(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _out: BigNumberish,
      _minBondOut: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "partialYTLiquidationSpecificOut(address,uint256,address,address,uint256,int256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _out: BigNumberish,
      _minBondOut: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    auctionYTLiquidation(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _bidYield: BigNumberish,
      _minBondRatio: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "auctionYTLiquidation(address,uint256,address,address,uint256,int256,uint256)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _bidYield: BigNumberish,
      _minBondRatio: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bidOnYTLiquidation(
      _index: BigNumberish,
      _bidYield: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bidOnYTLiquidation(uint256,uint256,uint256)"(
      _index: BigNumberish,
      _bidYield: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimYTLiquidation(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimYTLiquidation(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    instantYTLiquidation(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "instantYTLiquidation(address,uint256,address,address,uint256,uint256,int256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    partialYTLiquidationSpecificIn(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "partialYTLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,int256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _minBondRatio: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    partialYTLiquidationSpecificOut(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _out: BigNumberish,
      _minBondOut: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "partialYTLiquidationSpecificOut(address,uint256,address,address,uint256,int256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPborrowed: string,
      _FCPsupplied: string,
      _out: BigNumberish,
      _minBondOut: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
