/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DividendEnabledDataInterface extends ethers.utils.Interface {
  functions: {
    "YTaddress()": FunctionFragment;
    "ZCBaddress()": FunctionFragment;
    "activeTotalSupply()": FunctionFragment;
    "contractBondDividend(uint256)": FunctionFragment;
    "contractYieldDividend(uint256)": FunctionFragment;
    "ineligibleBalanceOf(address)": FunctionFragment;
    "lastWithdraw()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "YTaddress", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ZCBaddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractBondDividend",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractYieldDividend",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ineligibleBalanceOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lastWithdraw",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "YTaddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ZCBaddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activeTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractBondDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractYieldDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ineligibleBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastWithdraw",
    data: BytesLike
  ): Result;

  events: {};
}

export class DividendEnabledData extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DividendEnabledDataInterface;

  functions: {
    YTaddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "YTaddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    ZCBaddress(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "ZCBaddress()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    activeTotalSupply(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "activeTotalSupply()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    contractBondDividend(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "contractBondDividend(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    contractYieldDividend(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "contractYieldDividend(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    ineligibleBalanceOf(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "ineligibleBalanceOf(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    lastWithdraw(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "lastWithdraw()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  YTaddress(overrides?: CallOverrides): Promise<string>;

  "YTaddress()"(overrides?: CallOverrides): Promise<string>;

  ZCBaddress(overrides?: CallOverrides): Promise<string>;

  "ZCBaddress()"(overrides?: CallOverrides): Promise<string>;

  activeTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "activeTotalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  contractBondDividend(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "contractBondDividend(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  contractYieldDividend(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "contractYieldDividend(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ineligibleBalanceOf(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "ineligibleBalanceOf(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lastWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

  "lastWithdraw()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    YTaddress(overrides?: CallOverrides): Promise<string>;

    "YTaddress()"(overrides?: CallOverrides): Promise<string>;

    ZCBaddress(overrides?: CallOverrides): Promise<string>;

    "ZCBaddress()"(overrides?: CallOverrides): Promise<string>;

    activeTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "activeTotalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    contractBondDividend(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "contractBondDividend(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractYieldDividend(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "contractYieldDividend(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ineligibleBalanceOf(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ineligibleBalanceOf(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

    "lastWithdraw()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    YTaddress(overrides?: CallOverrides): Promise<BigNumber>;

    "YTaddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    ZCBaddress(overrides?: CallOverrides): Promise<BigNumber>;

    "ZCBaddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    activeTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "activeTotalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    contractBondDividend(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "contractBondDividend(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractYieldDividend(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "contractYieldDividend(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ineligibleBalanceOf(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ineligibleBalanceOf(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

    "lastWithdraw()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    YTaddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "YTaddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ZCBaddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ZCBaddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    activeTotalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "activeTotalSupply()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractBondDividend(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "contractBondDividend(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractYieldDividend(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "contractYieldDividend(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ineligibleBalanceOf(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ineligibleBalanceOf(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastWithdraw(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lastWithdraw()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
