/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IdbsfVaultManagerFlashReceiverInterface
  extends ethers.utils.Interface {
  functions: {
    "onFlashLoan(address,address,address,uint256,int256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "onFlashLoan",
    values: [string, string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "onFlashLoan",
    data: BytesLike
  ): Result;

  events: {};
}

export class IdbsfVaultManagerFlashReceiver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IdbsfVaultManagerFlashReceiverInterface;

  functions: {
    onFlashLoan(
      _vaultOwner: string,
      _prevStateAssetSupplied: string,
      _prevStateAssetBorrowed: string,
      _prevStateAmountSupplied: BigNumberish,
      _changeBorrowedPrevDebtAsset: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onFlashLoan(address,address,address,uint256,int256,bytes)"(
      _vaultOwner: string,
      _prevStateAssetSupplied: string,
      _prevStateAssetBorrowed: string,
      _prevStateAmountSupplied: BigNumberish,
      _changeBorrowedPrevDebtAsset: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  onFlashLoan(
    _vaultOwner: string,
    _prevStateAssetSupplied: string,
    _prevStateAssetBorrowed: string,
    _prevStateAmountSupplied: BigNumberish,
    _changeBorrowedPrevDebtAsset: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onFlashLoan(address,address,address,uint256,int256,bytes)"(
    _vaultOwner: string,
    _prevStateAssetSupplied: string,
    _prevStateAssetBorrowed: string,
    _prevStateAmountSupplied: BigNumberish,
    _changeBorrowedPrevDebtAsset: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    onFlashLoan(
      _vaultOwner: string,
      _prevStateAssetSupplied: string,
      _prevStateAssetBorrowed: string,
      _prevStateAmountSupplied: BigNumberish,
      _changeBorrowedPrevDebtAsset: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "onFlashLoan(address,address,address,uint256,int256,bytes)"(
      _vaultOwner: string,
      _prevStateAssetSupplied: string,
      _prevStateAssetBorrowed: string,
      _prevStateAmountSupplied: BigNumberish,
      _changeBorrowedPrevDebtAsset: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    onFlashLoan(
      _vaultOwner: string,
      _prevStateAssetSupplied: string,
      _prevStateAssetBorrowed: string,
      _prevStateAmountSupplied: BigNumberish,
      _changeBorrowedPrevDebtAsset: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onFlashLoan(address,address,address,uint256,int256,bytes)"(
      _vaultOwner: string,
      _prevStateAssetSupplied: string,
      _prevStateAssetBorrowed: string,
      _prevStateAmountSupplied: BigNumberish,
      _changeBorrowedPrevDebtAsset: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    onFlashLoan(
      _vaultOwner: string,
      _prevStateAssetSupplied: string,
      _prevStateAssetBorrowed: string,
      _prevStateAmountSupplied: BigNumberish,
      _changeBorrowedPrevDebtAsset: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onFlashLoan(address,address,address,uint256,int256,bytes)"(
      _vaultOwner: string,
      _prevStateAssetSupplied: string,
      _prevStateAssetBorrowed: string,
      _prevStateAmountSupplied: BigNumberish,
      _changeBorrowedPrevDebtAsset: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
