/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IDividendInterface extends ethers.utils.Interface {
  functions: {
    "claimDividend(address)": FunctionFragment;
    "contractClaimDividend()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimDividend",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "contractClaimDividend",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "claimDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractClaimDividend",
    data: BytesLike
  ): Result;

  events: {};
}

export class IDividend extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDividendInterface;

  functions: {
    claimDividend(
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimDividend(address)"(
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    contractClaimDividend(overrides?: Overrides): Promise<ContractTransaction>;

    "contractClaimDividend()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  claimDividend(
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimDividend(address)"(
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  contractClaimDividend(overrides?: Overrides): Promise<ContractTransaction>;

  "contractClaimDividend()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    claimDividend(_to: string, overrides?: CallOverrides): Promise<void>;

    "claimDividend(address)"(
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    contractClaimDividend(overrides?: CallOverrides): Promise<void>;

    "contractClaimDividend()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    claimDividend(_to: string, overrides?: Overrides): Promise<BigNumber>;

    "claimDividend(address)"(
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    contractClaimDividend(overrides?: Overrides): Promise<BigNumber>;

    "contractClaimDividend()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    claimDividend(
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimDividend(address)"(
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    contractClaimDividend(overrides?: Overrides): Promise<PopulatedTransaction>;

    "contractClaimDividend()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
