/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface InfoOracleInterface extends ethers.utils.Interface {
  functions: {
    "DelegatedControllers(address)": FunctionFragment;
    "FCPOrderbookFeeBips(address)": FunctionFragment;
    "FCPtoWrapper(address,address)": FunctionFragment;
    "MinimumOrderbookFee()": FunctionFragment;
    "StabilityFeeAPR(address,address)": FunctionFragment;
    "TreasuryFeeIsCollected()": FunctionFragment;
    "WrapperOrderbookFeeBips(address)": FunctionFragment;
    "WrapperToYTFeeConst(address)": FunctionFragment;
    "WrapperToYTSlippageConst(address)": FunctionFragment;
    "WrapperToZCBFeeConst(address)": FunctionFragment;
    "YTammFeeConstants(address)": FunctionFragment;
    "YTammSlippageConstants(address)": FunctionFragment;
    "ZCBammFeeConstants(address)": FunctionFragment;
    "bipsToTreasury()": FunctionFragment;
    "collateralWhitelist(address,address)": FunctionFragment;
    "getOrderbookFeeBips(address)": FunctionFragment;
    "getSlippageConstant(address)": FunctionFragment;
    "getYTammFeeConstant(address)": FunctionFragment;
    "getZCBammFeeConstant(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "sendTo()": FunctionFragment;
    "setAmmFeeConstants(address,uint256,uint256)": FunctionFragment;
    "setDelegatedController(address,address)": FunctionFragment;
    "setMinimumOrderbookFee(uint8)": FunctionFragment;
    "setOrderbookFeeConstant(address,uint8)": FunctionFragment;
    "setSlippageConstant(address,uint256)": FunctionFragment;
    "setStabilityFeeAPR(address,address,uint64)": FunctionFragment;
    "setToTreasuryFee(uint16)": FunctionFragment;
    "setTreasuryFeeIsCollected(bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "treasuryFee(uint256,uint256)": FunctionFragment;
    "whitelistAsset(address,address)": FunctionFragment;
    "whitelistFixCapitalPool(address,address)": FunctionFragment;
    "whitelistWrapper(address,address)": FunctionFragment;
    "wrapperSetAmmFeeConstants(address,uint256,uint256)": FunctionFragment;
    "wrapperSetOrderbookFeeConstant(address,uint8)": FunctionFragment;
    "wrapperSetSlippageConst(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DelegatedControllers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "FCPOrderbookFeeBips",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "FCPtoWrapper",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "MinimumOrderbookFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "StabilityFeeAPR",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "TreasuryFeeIsCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WrapperOrderbookFeeBips",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "WrapperToYTFeeConst",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "WrapperToYTSlippageConst",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "WrapperToZCBFeeConst",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "YTammFeeConstants",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "YTammSlippageConstants",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ZCBammFeeConstants",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "bipsToTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralWhitelist",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderbookFeeBips",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSlippageConstant",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getYTammFeeConstant",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getZCBammFeeConstant",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "sendTo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAmmFeeConstants",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelegatedController",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumOrderbookFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrderbookFeeConstant",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippageConstant",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStabilityFeeAPR",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setToTreasuryFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryFeeIsCollected",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistAsset",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistFixCapitalPool",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistWrapper",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapperSetAmmFeeConstants",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapperSetOrderbookFeeConstant",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapperSetSlippageConst",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DelegatedControllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FCPOrderbookFeeBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FCPtoWrapper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MinimumOrderbookFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "StabilityFeeAPR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TreasuryFeeIsCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WrapperOrderbookFeeBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WrapperToYTFeeConst",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WrapperToYTSlippageConst",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WrapperToZCBFeeConst",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "YTammFeeConstants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "YTammSlippageConstants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ZCBammFeeConstants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bipsToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderbookFeeBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSlippageConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYTammFeeConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getZCBammFeeConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAmmFeeConstants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDelegatedController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumOrderbookFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrderbookFeeConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlippageConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStabilityFeeAPR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setToTreasuryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryFeeIsCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistFixCapitalPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistWrapper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrapperSetAmmFeeConstants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrapperSetOrderbookFeeConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrapperSetSlippageConst",
    data: BytesLike
  ): Result;

  events: {};
}

export class InfoOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: InfoOracleInterface;

  functions: {
    DelegatedControllers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "DelegatedControllers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    FCPOrderbookFeeBips(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "FCPOrderbookFeeBips(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    FCPtoWrapper(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "FCPtoWrapper(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    MinimumOrderbookFee(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    "MinimumOrderbookFee()"(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    StabilityFeeAPR(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "StabilityFeeAPR(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    TreasuryFeeIsCollected(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "TreasuryFeeIsCollected()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    WrapperOrderbookFeeBips(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "WrapperOrderbookFeeBips(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    WrapperToYTFeeConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "WrapperToYTFeeConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    WrapperToYTSlippageConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "WrapperToYTSlippageConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    WrapperToZCBFeeConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "WrapperToZCBFeeConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    YTammFeeConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "YTammFeeConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    YTammSlippageConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "YTammSlippageConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    ZCBammFeeConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "ZCBammFeeConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    bipsToTreasury(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    "bipsToTreasury()"(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    collateralWhitelist(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "collateralWhitelist(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getOrderbookFeeBips(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      FeeBips: number;
      0: number;
    }>;

    "getOrderbookFeeBips(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      FeeBips: number;
      0: number;
    }>;

    getSlippageConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      SlippageConstant: BigNumber;
      0: BigNumber;
    }>;

    "getSlippageConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      SlippageConstant: BigNumber;
      0: BigNumber;
    }>;

    getYTammFeeConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      FeeConstant: BigNumber;
      0: BigNumber;
    }>;

    "getYTammFeeConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      FeeConstant: BigNumber;
      0: BigNumber;
    }>;

    getZCBammFeeConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      FeeConstant: BigNumber;
      0: BigNumber;
    }>;

    "getZCBammFeeConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      FeeConstant: BigNumber;
      0: BigNumber;
    }>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    sendTo(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "sendTo()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    setAmmFeeConstants(
      _fixCapitalPoolAddress: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setAmmFeeConstants(address,uint256,uint256)"(
      _fixCapitalPoolAddress: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setDelegatedController(
      _contract: string,
      _manager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDelegatedController(address,address)"(
      _contract: string,
      _manager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setMinimumOrderbookFee(
      _minimumOrderbookFee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setMinimumOrderbookFee(uint8)"(
      _minimumOrderbookFee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setOrderbookFeeConstant(
      _fixCapitalPoolAddress: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setOrderbookFeeConstant(address,uint8)"(
      _fixCapitalPoolAddress: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setSlippageConstant(
      _fixCapitalPoolAddress: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setSlippageConstant(address,uint256)"(
      _fixCapitalPoolAddress: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setStabilityFeeAPR(
      _vaultFactoryAddress: string,
      _wrapperAsset: string,
      _stabilityFeeAPR: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setStabilityFeeAPR(address,address,uint64)"(
      _vaultFactoryAddress: string,
      _wrapperAsset: string,
      _stabilityFeeAPR: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setToTreasuryFee(
      _bipsToTreasury: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setToTreasuryFee(uint16)"(
      _bipsToTreasury: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setTreasuryFeeIsCollected(
      _TreasuryFeeIsCollected: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setTreasuryFeeIsCollected(bool)"(
      _TreasuryFeeIsCollected: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    treasuryFee(
      larger: BigNumberish,
      smaller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      toTreasury: BigNumber;
      _sendTo: string;
      0: BigNumber;
      1: string;
    }>;

    "treasuryFee(uint256,uint256)"(
      larger: BigNumberish,
      smaller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      toTreasury: BigNumber;
      _sendTo: string;
      0: BigNumber;
      1: string;
    }>;

    whitelistAsset(
      _vaultFactoryAddress: string,
      _assetAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "whitelistAsset(address,address)"(
      _vaultFactoryAddress: string,
      _assetAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    whitelistFixCapitalPool(
      _vaultFactoryAddress: string,
      _FCPaddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "whitelistFixCapitalPool(address,address)"(
      _vaultFactoryAddress: string,
      _FCPaddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    whitelistWrapper(
      _vaultFactoryAddress: string,
      _wrapperAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "whitelistWrapper(address,address)"(
      _vaultFactoryAddress: string,
      _wrapperAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    wrapperSetAmmFeeConstants(
      _wrapper: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "wrapperSetAmmFeeConstants(address,uint256,uint256)"(
      _wrapper: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    wrapperSetOrderbookFeeConstant(
      _wrapper: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "wrapperSetOrderbookFeeConstant(address,uint8)"(
      _wrapper: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    wrapperSetSlippageConst(
      _wrapper: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "wrapperSetSlippageConst(address,uint256)"(
      _wrapper: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  DelegatedControllers(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "DelegatedControllers(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  FCPOrderbookFeeBips(arg0: string, overrides?: CallOverrides): Promise<number>;

  "FCPOrderbookFeeBips(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<number>;

  FCPtoWrapper(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "FCPtoWrapper(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  MinimumOrderbookFee(overrides?: CallOverrides): Promise<number>;

  "MinimumOrderbookFee()"(overrides?: CallOverrides): Promise<number>;

  StabilityFeeAPR(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "StabilityFeeAPR(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  TreasuryFeeIsCollected(overrides?: CallOverrides): Promise<boolean>;

  "TreasuryFeeIsCollected()"(overrides?: CallOverrides): Promise<boolean>;

  WrapperOrderbookFeeBips(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<number>;

  "WrapperOrderbookFeeBips(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<number>;

  WrapperToYTFeeConst(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "WrapperToYTFeeConst(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  WrapperToYTSlippageConst(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "WrapperToYTSlippageConst(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  WrapperToZCBFeeConst(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "WrapperToZCBFeeConst(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  YTammFeeConstants(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "YTammFeeConstants(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  YTammSlippageConstants(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "YTammSlippageConstants(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ZCBammFeeConstants(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "ZCBammFeeConstants(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  bipsToTreasury(overrides?: CallOverrides): Promise<number>;

  "bipsToTreasury()"(overrides?: CallOverrides): Promise<number>;

  collateralWhitelist(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "collateralWhitelist(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getOrderbookFeeBips(
    _fixCapitalPoolAddress: string,
    overrides?: CallOverrides
  ): Promise<number>;

  "getOrderbookFeeBips(address)"(
    _fixCapitalPoolAddress: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getSlippageConstant(
    _fixCapitalPoolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getSlippageConstant(address)"(
    _fixCapitalPoolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getYTammFeeConstant(
    _fixCapitalPoolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getYTammFeeConstant(address)"(
    _fixCapitalPoolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getZCBammFeeConstant(
    _fixCapitalPoolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getZCBammFeeConstant(address)"(
    _fixCapitalPoolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  sendTo(overrides?: CallOverrides): Promise<string>;

  "sendTo()"(overrides?: CallOverrides): Promise<string>;

  setAmmFeeConstants(
    _fixCapitalPoolAddress: string,
    _ZCBammFeeConstant: BigNumberish,
    _YTammFeeConstant: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setAmmFeeConstants(address,uint256,uint256)"(
    _fixCapitalPoolAddress: string,
    _ZCBammFeeConstant: BigNumberish,
    _YTammFeeConstant: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setDelegatedController(
    _contract: string,
    _manager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDelegatedController(address,address)"(
    _contract: string,
    _manager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setMinimumOrderbookFee(
    _minimumOrderbookFee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setMinimumOrderbookFee(uint8)"(
    _minimumOrderbookFee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setOrderbookFeeConstant(
    _fixCapitalPoolAddress: string,
    _orderbookFeeBips: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setOrderbookFeeConstant(address,uint8)"(
    _fixCapitalPoolAddress: string,
    _orderbookFeeBips: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setSlippageConstant(
    _fixCapitalPoolAddress: string,
    _SlippageConstant: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setSlippageConstant(address,uint256)"(
    _fixCapitalPoolAddress: string,
    _SlippageConstant: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setStabilityFeeAPR(
    _vaultFactoryAddress: string,
    _wrapperAsset: string,
    _stabilityFeeAPR: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setStabilityFeeAPR(address,address,uint64)"(
    _vaultFactoryAddress: string,
    _wrapperAsset: string,
    _stabilityFeeAPR: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setToTreasuryFee(
    _bipsToTreasury: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setToTreasuryFee(uint16)"(
    _bipsToTreasury: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setTreasuryFeeIsCollected(
    _TreasuryFeeIsCollected: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setTreasuryFeeIsCollected(bool)"(
    _TreasuryFeeIsCollected: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  treasuryFee(
    larger: BigNumberish,
    smaller: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    toTreasury: BigNumber;
    _sendTo: string;
    0: BigNumber;
    1: string;
  }>;

  "treasuryFee(uint256,uint256)"(
    larger: BigNumberish,
    smaller: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    toTreasury: BigNumber;
    _sendTo: string;
    0: BigNumber;
    1: string;
  }>;

  whitelistAsset(
    _vaultFactoryAddress: string,
    _assetAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "whitelistAsset(address,address)"(
    _vaultFactoryAddress: string,
    _assetAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  whitelistFixCapitalPool(
    _vaultFactoryAddress: string,
    _FCPaddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "whitelistFixCapitalPool(address,address)"(
    _vaultFactoryAddress: string,
    _FCPaddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  whitelistWrapper(
    _vaultFactoryAddress: string,
    _wrapperAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "whitelistWrapper(address,address)"(
    _vaultFactoryAddress: string,
    _wrapperAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  wrapperSetAmmFeeConstants(
    _wrapper: string,
    _ZCBammFeeConstant: BigNumberish,
    _YTammFeeConstant: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "wrapperSetAmmFeeConstants(address,uint256,uint256)"(
    _wrapper: string,
    _ZCBammFeeConstant: BigNumberish,
    _YTammFeeConstant: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  wrapperSetOrderbookFeeConstant(
    _wrapper: string,
    _orderbookFeeBips: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "wrapperSetOrderbookFeeConstant(address,uint8)"(
    _wrapper: string,
    _orderbookFeeBips: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  wrapperSetSlippageConst(
    _wrapper: string,
    _SlippageConstant: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "wrapperSetSlippageConst(address,uint256)"(
    _wrapper: string,
    _SlippageConstant: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    DelegatedControllers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "DelegatedControllers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    FCPOrderbookFeeBips(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<number>;

    "FCPOrderbookFeeBips(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<number>;

    FCPtoWrapper(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "FCPtoWrapper(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    MinimumOrderbookFee(overrides?: CallOverrides): Promise<number>;

    "MinimumOrderbookFee()"(overrides?: CallOverrides): Promise<number>;

    StabilityFeeAPR(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "StabilityFeeAPR(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TreasuryFeeIsCollected(overrides?: CallOverrides): Promise<boolean>;

    "TreasuryFeeIsCollected()"(overrides?: CallOverrides): Promise<boolean>;

    WrapperOrderbookFeeBips(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<number>;

    "WrapperOrderbookFeeBips(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<number>;

    WrapperToYTFeeConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "WrapperToYTFeeConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    WrapperToYTSlippageConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "WrapperToYTSlippageConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    WrapperToZCBFeeConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "WrapperToZCBFeeConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    YTammFeeConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "YTammFeeConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    YTammSlippageConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "YTammSlippageConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ZCBammFeeConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ZCBammFeeConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bipsToTreasury(overrides?: CallOverrides): Promise<number>;

    "bipsToTreasury()"(overrides?: CallOverrides): Promise<number>;

    collateralWhitelist(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "collateralWhitelist(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrderbookFeeBips(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<number>;

    "getOrderbookFeeBips(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getSlippageConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSlippageConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getYTammFeeConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getYTammFeeConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZCBammFeeConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getZCBammFeeConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    sendTo(overrides?: CallOverrides): Promise<string>;

    "sendTo()"(overrides?: CallOverrides): Promise<string>;

    setAmmFeeConstants(
      _fixCapitalPoolAddress: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAmmFeeConstants(address,uint256,uint256)"(
      _fixCapitalPoolAddress: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDelegatedController(
      _contract: string,
      _manager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setDelegatedController(address,address)"(
      _contract: string,
      _manager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinimumOrderbookFee(
      _minimumOrderbookFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMinimumOrderbookFee(uint8)"(
      _minimumOrderbookFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setOrderbookFeeConstant(
      _fixCapitalPoolAddress: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setOrderbookFeeConstant(address,uint8)"(
      _fixCapitalPoolAddress: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSlippageConstant(
      _fixCapitalPoolAddress: string,
      _SlippageConstant: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setSlippageConstant(address,uint256)"(
      _fixCapitalPoolAddress: string,
      _SlippageConstant: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setStabilityFeeAPR(
      _vaultFactoryAddress: string,
      _wrapperAsset: string,
      _stabilityFeeAPR: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setStabilityFeeAPR(address,address,uint64)"(
      _vaultFactoryAddress: string,
      _wrapperAsset: string,
      _stabilityFeeAPR: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setToTreasuryFee(
      _bipsToTreasury: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setToTreasuryFee(uint16)"(
      _bipsToTreasury: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasuryFeeIsCollected(
      _TreasuryFeeIsCollected: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setTreasuryFeeIsCollected(bool)"(
      _TreasuryFeeIsCollected: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuryFee(
      larger: BigNumberish,
      smaller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      toTreasury: BigNumber;
      _sendTo: string;
      0: BigNumber;
      1: string;
    }>;

    "treasuryFee(uint256,uint256)"(
      larger: BigNumberish,
      smaller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      toTreasury: BigNumber;
      _sendTo: string;
      0: BigNumber;
      1: string;
    }>;

    whitelistAsset(
      _vaultFactoryAddress: string,
      _assetAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "whitelistAsset(address,address)"(
      _vaultFactoryAddress: string,
      _assetAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistFixCapitalPool(
      _vaultFactoryAddress: string,
      _FCPaddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "whitelistFixCapitalPool(address,address)"(
      _vaultFactoryAddress: string,
      _FCPaddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistWrapper(
      _vaultFactoryAddress: string,
      _wrapperAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "whitelistWrapper(address,address)"(
      _vaultFactoryAddress: string,
      _wrapperAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    wrapperSetAmmFeeConstants(
      _wrapper: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "wrapperSetAmmFeeConstants(address,uint256,uint256)"(
      _wrapper: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    wrapperSetOrderbookFeeConstant(
      _wrapper: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "wrapperSetOrderbookFeeConstant(address,uint8)"(
      _wrapper: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    wrapperSetSlippageConst(
      _wrapper: string,
      _SlippageConstant: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "wrapperSetSlippageConst(address,uint256)"(
      _wrapper: string,
      _SlippageConstant: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    DelegatedControllers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "DelegatedControllers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    FCPOrderbookFeeBips(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "FCPOrderbookFeeBips(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    FCPtoWrapper(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "FCPtoWrapper(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    MinimumOrderbookFee(overrides?: CallOverrides): Promise<BigNumber>;

    "MinimumOrderbookFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    StabilityFeeAPR(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "StabilityFeeAPR(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TreasuryFeeIsCollected(overrides?: CallOverrides): Promise<BigNumber>;

    "TreasuryFeeIsCollected()"(overrides?: CallOverrides): Promise<BigNumber>;

    WrapperOrderbookFeeBips(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "WrapperOrderbookFeeBips(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    WrapperToYTFeeConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "WrapperToYTFeeConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    WrapperToYTSlippageConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "WrapperToYTSlippageConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    WrapperToZCBFeeConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "WrapperToZCBFeeConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    YTammFeeConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "YTammFeeConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    YTammSlippageConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "YTammSlippageConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ZCBammFeeConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ZCBammFeeConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bipsToTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    "bipsToTreasury()"(overrides?: CallOverrides): Promise<BigNumber>;

    collateralWhitelist(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collateralWhitelist(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrderbookFeeBips(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getOrderbookFeeBips(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSlippageConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSlippageConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getYTammFeeConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getYTammFeeConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZCBammFeeConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getZCBammFeeConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    sendTo(overrides?: CallOverrides): Promise<BigNumber>;

    "sendTo()"(overrides?: CallOverrides): Promise<BigNumber>;

    setAmmFeeConstants(
      _fixCapitalPoolAddress: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setAmmFeeConstants(address,uint256,uint256)"(
      _fixCapitalPoolAddress: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setDelegatedController(
      _contract: string,
      _manager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setDelegatedController(address,address)"(
      _contract: string,
      _manager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setMinimumOrderbookFee(
      _minimumOrderbookFee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setMinimumOrderbookFee(uint8)"(
      _minimumOrderbookFee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setOrderbookFeeConstant(
      _fixCapitalPoolAddress: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setOrderbookFeeConstant(address,uint8)"(
      _fixCapitalPoolAddress: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setSlippageConstant(
      _fixCapitalPoolAddress: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setSlippageConstant(address,uint256)"(
      _fixCapitalPoolAddress: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setStabilityFeeAPR(
      _vaultFactoryAddress: string,
      _wrapperAsset: string,
      _stabilityFeeAPR: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setStabilityFeeAPR(address,address,uint64)"(
      _vaultFactoryAddress: string,
      _wrapperAsset: string,
      _stabilityFeeAPR: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setToTreasuryFee(
      _bipsToTreasury: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setToTreasuryFee(uint16)"(
      _bipsToTreasury: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setTreasuryFeeIsCollected(
      _TreasuryFeeIsCollected: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setTreasuryFeeIsCollected(bool)"(
      _TreasuryFeeIsCollected: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    treasuryFee(
      larger: BigNumberish,
      smaller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "treasuryFee(uint256,uint256)"(
      larger: BigNumberish,
      smaller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    whitelistAsset(
      _vaultFactoryAddress: string,
      _assetAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "whitelistAsset(address,address)"(
      _vaultFactoryAddress: string,
      _assetAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    whitelistFixCapitalPool(
      _vaultFactoryAddress: string,
      _FCPaddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "whitelistFixCapitalPool(address,address)"(
      _vaultFactoryAddress: string,
      _FCPaddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    whitelistWrapper(
      _vaultFactoryAddress: string,
      _wrapperAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "whitelistWrapper(address,address)"(
      _vaultFactoryAddress: string,
      _wrapperAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    wrapperSetAmmFeeConstants(
      _wrapper: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "wrapperSetAmmFeeConstants(address,uint256,uint256)"(
      _wrapper: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    wrapperSetOrderbookFeeConstant(
      _wrapper: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "wrapperSetOrderbookFeeConstant(address,uint8)"(
      _wrapper: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    wrapperSetSlippageConst(
      _wrapper: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "wrapperSetSlippageConst(address,uint256)"(
      _wrapper: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DelegatedControllers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "DelegatedControllers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    FCPOrderbookFeeBips(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "FCPOrderbookFeeBips(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    FCPtoWrapper(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "FCPtoWrapper(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MinimumOrderbookFee(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MinimumOrderbookFee()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    StabilityFeeAPR(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "StabilityFeeAPR(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TreasuryFeeIsCollected(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "TreasuryFeeIsCollected()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    WrapperOrderbookFeeBips(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "WrapperOrderbookFeeBips(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    WrapperToYTFeeConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "WrapperToYTFeeConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    WrapperToYTSlippageConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "WrapperToYTSlippageConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    WrapperToZCBFeeConst(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "WrapperToZCBFeeConst(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    YTammFeeConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "YTammFeeConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    YTammSlippageConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "YTammSlippageConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ZCBammFeeConstants(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ZCBammFeeConstants(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bipsToTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bipsToTreasury()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collateralWhitelist(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collateralWhitelist(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrderbookFeeBips(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getOrderbookFeeBips(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSlippageConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSlippageConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getYTammFeeConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getYTammFeeConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getZCBammFeeConstant(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getZCBammFeeConstant(address)"(
      _fixCapitalPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendTo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sendTo()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAmmFeeConstants(
      _fixCapitalPoolAddress: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setAmmFeeConstants(address,uint256,uint256)"(
      _fixCapitalPoolAddress: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setDelegatedController(
      _contract: string,
      _manager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDelegatedController(address,address)"(
      _contract: string,
      _manager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setMinimumOrderbookFee(
      _minimumOrderbookFee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setMinimumOrderbookFee(uint8)"(
      _minimumOrderbookFee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setOrderbookFeeConstant(
      _fixCapitalPoolAddress: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setOrderbookFeeConstant(address,uint8)"(
      _fixCapitalPoolAddress: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setSlippageConstant(
      _fixCapitalPoolAddress: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setSlippageConstant(address,uint256)"(
      _fixCapitalPoolAddress: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setStabilityFeeAPR(
      _vaultFactoryAddress: string,
      _wrapperAsset: string,
      _stabilityFeeAPR: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setStabilityFeeAPR(address,address,uint64)"(
      _vaultFactoryAddress: string,
      _wrapperAsset: string,
      _stabilityFeeAPR: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setToTreasuryFee(
      _bipsToTreasury: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setToTreasuryFee(uint16)"(
      _bipsToTreasury: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setTreasuryFeeIsCollected(
      _TreasuryFeeIsCollected: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setTreasuryFeeIsCollected(bool)"(
      _TreasuryFeeIsCollected: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    treasuryFee(
      larger: BigNumberish,
      smaller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "treasuryFee(uint256,uint256)"(
      larger: BigNumberish,
      smaller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistAsset(
      _vaultFactoryAddress: string,
      _assetAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "whitelistAsset(address,address)"(
      _vaultFactoryAddress: string,
      _assetAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    whitelistFixCapitalPool(
      _vaultFactoryAddress: string,
      _FCPaddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "whitelistFixCapitalPool(address,address)"(
      _vaultFactoryAddress: string,
      _FCPaddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    whitelistWrapper(
      _vaultFactoryAddress: string,
      _wrapperAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "whitelistWrapper(address,address)"(
      _vaultFactoryAddress: string,
      _wrapperAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    wrapperSetAmmFeeConstants(
      _wrapper: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "wrapperSetAmmFeeConstants(address,uint256,uint256)"(
      _wrapper: string,
      _ZCBammFeeConstant: BigNumberish,
      _YTammFeeConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    wrapperSetOrderbookFeeConstant(
      _wrapper: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "wrapperSetOrderbookFeeConstant(address,uint8)"(
      _wrapper: string,
      _orderbookFeeBips: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    wrapperSetSlippageConst(
      _wrapper: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "wrapperSetSlippageConst(address,uint256)"(
      _wrapper: string,
      _SlippageConstant: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
