/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IOrganizer } from "./IOrganizer";

export class IOrganizerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOrganizer {
    return new Contract(address, _abi, signerOrProvider) as IOrganizer;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "FCPaddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "BaseWrapperAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "maturity",
        type: "uint40",
      },
    ],
    name: "FixCapitalPoolDeployment",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "OrderbookAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "BaseFCPaddress",
        type: "address",
      },
    ],
    name: "OrderbookDeployment",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "wrapperAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "underlyingAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "wrapperType",
        type: "uint8",
      },
    ],
    name: "WrapperDeployment",
    type: "event",
  },
  {
    inputs: [],
    name: "DeploySwapRouter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "FixCapitalPoolDeployerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "InfoOracleAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "NGBwrapperDeployerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OrderbookDeployerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_FCPaddress",
        type: "address",
      },
    ],
    name: "Orderbooks",
    outputs: [
      {
        internalType: "address",
        name: "OrderbookAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "QuickDepositorAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SwapRouterAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "YTammDeployerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_FCPaddress",
        type: "address",
      },
    ],
    name: "YTamms",
    outputs: [
      {
        internalType: "address",
        name: "YTammAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ZCB_YT_DeployerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ZCBammDeployerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_FCPaddress",
        type: "address",
      },
    ],
    name: "ZCBamms",
    outputs: [
      {
        internalType: "address",
        name: "ZCBammAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wrapperAddress",
        type: "address",
      },
      {
        internalType: "uint40",
        name: "_maturity",
        type: "uint40",
      },
    ],
    name: "deployFixCapitalPoolInstance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_underlyingAssetAddress",
        type: "address",
      },
    ],
    name: "deployNGBWrapper",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
    ],
    name: "deployOrderbook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
    ],
    name: "deployYTamm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
    ],
    name: "deployZCBamm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_FCPaddress",
        type: "address",
      },
    ],
    name: "fixCapitalPoolToWrapper",
    outputs: [
      {
        internalType: "address",
        name: "wrapperAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wrapperAddress",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_setTo",
        type: "bool",
      },
    ],
    name: "setVerified",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wrapperAddress",
        type: "address",
      },
    ],
    name: "wrapperIsVerified",
    outputs: [
      {
        internalType: "bool",
        name: "isVerified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
