/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ISwapRouter } from "./ISwapRouter";

export class ISwapRouterFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISwapRouter {
    return new Contract(address, _abi, signerOrProvider) as ISwapRouter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_minUout",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_unwrap",
        type: "bool",
      },
    ],
    name: "LiquidateAllToUnderlying",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountZCB",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amountYT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minUout",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_unwrap",
        type: "bool",
      },
    ],
    name: "LiquidateSpecificToUnderlying",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountYT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_Uin",
        type: "uint256",
      },
    ],
    name: "SwapUtoYT_ZCBamm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountYT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minUout",
        type: "uint256",
      },
    ],
    name: "SwapYTtoU_ZCBamm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountYT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minZCBout",
        type: "uint256",
      },
    ],
    name: "SwapYTtoZCB",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountYT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minZCBout",
        type: "uint256",
      },
    ],
    name: "SwapYTtoZCB_ZCBamm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountYT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxZCBin",
        type: "uint256",
      },
    ],
    name: "SwapZCBtoYT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountYT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxZCBin",
        type: "uint256",
      },
    ],
    name: "SwapZCBtoYT_ZCBamm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "int128",
        name: "_amount",
        type: "int128",
      },
      {
        internalType: "uint256",
        name: "_maxATkn",
        type: "uint256",
      },
    ],
    name: "UnitToYT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fixCapitalPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minZCBout",
        type: "uint256",
      },
    ],
    name: "UnitToZCB",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
