/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IytVaultManagerFlashReceiver } from "./IytVaultManagerFlashReceiver";

export class IytVaultManagerFlashReceiverFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IytVaultManagerFlashReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IytVaultManagerFlashReceiver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_vaultOwner",
        type: "address",
      },
      {
        internalType: "address",
        name: "_prevStateFCPSupplied",
        type: "address",
      },
      {
        internalType: "address",
        name: "_prevStateFCPBorrowed",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_prevStateYieldSupplied",
        type: "uint256",
      },
      {
        internalType: "int256",
        name: "_prevStateBondSupplied",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "_prevStateAmountBorrowed",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "onFlashLoan",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
