/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface NsfVaultFactoryDelegate2Interface extends ethers.utils.Interface {
  functions: {
    "auctionLiquidation(address,uint256,address,address,uint256,uint256)": FunctionFragment;
    "bidOnLiquidation(uint256,uint256,uint256)": FunctionFragment;
    "claimLiquidation(uint256,address)": FunctionFragment;
    "instantLiquidation(address,uint256,address,address,uint256,uint256,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "partialLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,address)": FunctionFragment;
    "partialLiquidationSpecificOut(address,uint256,address,address,uint256,uint256,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "auctionLiquidation",
    values: [string, BigNumberish, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bidOnLiquidation",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimLiquidation",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "instantLiquidation",
    values: [
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "partialLiquidationSpecificIn",
    values: [
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "partialLiquidationSpecificOut",
    values: [
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidOnLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "instantLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "partialLiquidationSpecificIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partialLiquidationSpecificOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {};
}

export class NsfVaultFactoryDelegate2 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: NsfVaultFactoryDelegate2Interface;

  functions: {
    auctionLiquidation(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "auctionLiquidation(address,uint256,address,address,uint256,uint256)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bidOnLiquidation(
      _index: BigNumberish,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bidOnLiquidation(uint256,uint256,uint256)"(
      _index: BigNumberish,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimLiquidation(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimLiquidation(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    instantLiquidation(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "instantLiquidation(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    partialLiquidationSpecificIn(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "partialLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    partialLiquidationSpecificOut(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _out: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "partialLiquidationSpecificOut(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _out: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  auctionLiquidation(
    _owner: string,
    _index: BigNumberish,
    _assetBorrowed: string,
    _assetSupplied: string,
    _bid: BigNumberish,
    _amtIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "auctionLiquidation(address,uint256,address,address,uint256,uint256)"(
    _owner: string,
    _index: BigNumberish,
    _assetBorrowed: string,
    _assetSupplied: string,
    _bid: BigNumberish,
    _amtIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bidOnLiquidation(
    _index: BigNumberish,
    _bid: BigNumberish,
    _amtIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bidOnLiquidation(uint256,uint256,uint256)"(
    _index: BigNumberish,
    _bid: BigNumberish,
    _amtIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimLiquidation(
    _index: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimLiquidation(uint256,address)"(
    _index: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  instantLiquidation(
    _owner: string,
    _index: BigNumberish,
    _assetBorrowed: string,
    _assetSupplied: string,
    _maxIn: BigNumberish,
    _minOut: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "instantLiquidation(address,uint256,address,address,uint256,uint256,address)"(
    _owner: string,
    _index: BigNumberish,
    _assetBorrowed: string,
    _assetSupplied: string,
    _maxIn: BigNumberish,
    _minOut: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  partialLiquidationSpecificIn(
    _owner: string,
    _index: BigNumberish,
    _assetBorrowed: string,
    _assetSupplied: string,
    _in: BigNumberish,
    _minOut: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "partialLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,address)"(
    _owner: string,
    _index: BigNumberish,
    _assetBorrowed: string,
    _assetSupplied: string,
    _in: BigNumberish,
    _minOut: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  partialLiquidationSpecificOut(
    _owner: string,
    _index: BigNumberish,
    _assetBorrowed: string,
    _assetSupplied: string,
    _out: BigNumberish,
    _maxIn: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "partialLiquidationSpecificOut(address,uint256,address,address,uint256,uint256,address)"(
    _owner: string,
    _index: BigNumberish,
    _assetBorrowed: string,
    _assetSupplied: string,
    _out: BigNumberish,
    _maxIn: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    auctionLiquidation(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "auctionLiquidation(address,uint256,address,address,uint256,uint256)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    bidOnLiquidation(
      _index: BigNumberish,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "bidOnLiquidation(uint256,uint256,uint256)"(
      _index: BigNumberish,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimLiquidation(
      _index: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "claimLiquidation(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    instantLiquidation(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "instantLiquidation(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    partialLiquidationSpecificIn(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "partialLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    partialLiquidationSpecificOut(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _out: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "partialLiquidationSpecificOut(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _out: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    auctionLiquidation(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "auctionLiquidation(address,uint256,address,address,uint256,uint256)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bidOnLiquidation(
      _index: BigNumberish,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bidOnLiquidation(uint256,uint256,uint256)"(
      _index: BigNumberish,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimLiquidation(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimLiquidation(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    instantLiquidation(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "instantLiquidation(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    partialLiquidationSpecificIn(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "partialLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    partialLiquidationSpecificOut(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _out: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "partialLiquidationSpecificOut(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _out: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    auctionLiquidation(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "auctionLiquidation(address,uint256,address,address,uint256,uint256)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bidOnLiquidation(
      _index: BigNumberish,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bidOnLiquidation(uint256,uint256,uint256)"(
      _index: BigNumberish,
      _bid: BigNumberish,
      _amtIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimLiquidation(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimLiquidation(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    instantLiquidation(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "instantLiquidation(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _maxIn: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    partialLiquidationSpecificIn(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "partialLiquidationSpecificIn(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _in: BigNumberish,
      _minOut: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    partialLiquidationSpecificOut(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _out: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "partialLiquidationSpecificOut(address,uint256,address,address,uint256,uint256,address)"(
      _owner: string,
      _index: BigNumberish,
      _assetBorrowed: string,
      _assetSupplied: string,
      _out: BigNumberish,
      _maxIn: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
