/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SbnsfVaultFactoryDelegate3Interface extends ethers.utils.Interface {
  functions: {
    "adjustYTVault(address,uint256,address,address,uint256,int256,uint256,int128[3],bytes,address)": FunctionFragment;
    "closeYTVault(uint256,address)": FunctionFragment;
    "openYTVault(address,address,uint256,int256,uint256,uint256,int128,int128)": FunctionFragment;
    "owner()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "adjustYTVault",
    values: [
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish],
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeYTVault",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "openYTVault",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "adjustYTVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeYTVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openYTVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {};
}

export class SbnsfVaultFactoryDelegate3 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SbnsfVaultFactoryDelegate3Interface;

  functions: {
    adjustYTVault(
      _owner: string,
      _index: BigNumberish,
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _multipliers: [BigNumberish, BigNumberish, BigNumberish],
      _data: BytesLike,
      _receiverAddr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adjustYTVault(address,uint256,address,address,uint256,int256,uint256,int128[3],bytes,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _multipliers: [BigNumberish, BigNumberish, BigNumberish],
      _data: BytesLike,
      _receiverAddr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    closeYTVault(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "closeYTVault(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    openYTVault(
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _priceMultiplier: BigNumberish,
      _suppliedRateChange: BigNumberish,
      _borrowRateChange: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "openYTVault(address,address,uint256,int256,uint256,uint256,int128,int128)"(
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _priceMultiplier: BigNumberish,
      _suppliedRateChange: BigNumberish,
      _borrowRateChange: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  adjustYTVault(
    _owner: string,
    _index: BigNumberish,
    _FCPsupplied: string,
    _FCPborrowed: string,
    _yieldSupplied: BigNumberish,
    _bondSupplied: BigNumberish,
    _amountBorrowed: BigNumberish,
    _multipliers: [BigNumberish, BigNumberish, BigNumberish],
    _data: BytesLike,
    _receiverAddr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adjustYTVault(address,uint256,address,address,uint256,int256,uint256,int128[3],bytes,address)"(
    _owner: string,
    _index: BigNumberish,
    _FCPsupplied: string,
    _FCPborrowed: string,
    _yieldSupplied: BigNumberish,
    _bondSupplied: BigNumberish,
    _amountBorrowed: BigNumberish,
    _multipliers: [BigNumberish, BigNumberish, BigNumberish],
    _data: BytesLike,
    _receiverAddr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  closeYTVault(
    _index: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "closeYTVault(uint256,address)"(
    _index: BigNumberish,
    _to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  openYTVault(
    _FCPsupplied: string,
    _FCPborrowed: string,
    _yieldSupplied: BigNumberish,
    _bondSupplied: BigNumberish,
    _amountBorrowed: BigNumberish,
    _priceMultiplier: BigNumberish,
    _suppliedRateChange: BigNumberish,
    _borrowRateChange: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "openYTVault(address,address,uint256,int256,uint256,uint256,int128,int128)"(
    _FCPsupplied: string,
    _FCPborrowed: string,
    _yieldSupplied: BigNumberish,
    _bondSupplied: BigNumberish,
    _amountBorrowed: BigNumberish,
    _priceMultiplier: BigNumberish,
    _suppliedRateChange: BigNumberish,
    _borrowRateChange: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    adjustYTVault(
      _owner: string,
      _index: BigNumberish,
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _multipliers: [BigNumberish, BigNumberish, BigNumberish],
      _data: BytesLike,
      _receiverAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "adjustYTVault(address,uint256,address,address,uint256,int256,uint256,int128[3],bytes,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _multipliers: [BigNumberish, BigNumberish, BigNumberish],
      _data: BytesLike,
      _receiverAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    closeYTVault(
      _index: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "closeYTVault(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    openYTVault(
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _priceMultiplier: BigNumberish,
      _suppliedRateChange: BigNumberish,
      _borrowRateChange: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "openYTVault(address,address,uint256,int256,uint256,uint256,int128,int128)"(
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _priceMultiplier: BigNumberish,
      _suppliedRateChange: BigNumberish,
      _borrowRateChange: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    adjustYTVault(
      _owner: string,
      _index: BigNumberish,
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _multipliers: [BigNumberish, BigNumberish, BigNumberish],
      _data: BytesLike,
      _receiverAddr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adjustYTVault(address,uint256,address,address,uint256,int256,uint256,int128[3],bytes,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _multipliers: [BigNumberish, BigNumberish, BigNumberish],
      _data: BytesLike,
      _receiverAddr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    closeYTVault(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "closeYTVault(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    openYTVault(
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _priceMultiplier: BigNumberish,
      _suppliedRateChange: BigNumberish,
      _borrowRateChange: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "openYTVault(address,address,uint256,int256,uint256,uint256,int128,int128)"(
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _priceMultiplier: BigNumberish,
      _suppliedRateChange: BigNumberish,
      _borrowRateChange: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adjustYTVault(
      _owner: string,
      _index: BigNumberish,
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _multipliers: [BigNumberish, BigNumberish, BigNumberish],
      _data: BytesLike,
      _receiverAddr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adjustYTVault(address,uint256,address,address,uint256,int256,uint256,int128[3],bytes,address)"(
      _owner: string,
      _index: BigNumberish,
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _multipliers: [BigNumberish, BigNumberish, BigNumberish],
      _data: BytesLike,
      _receiverAddr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    closeYTVault(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "closeYTVault(uint256,address)"(
      _index: BigNumberish,
      _to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    openYTVault(
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _priceMultiplier: BigNumberish,
      _suppliedRateChange: BigNumberish,
      _borrowRateChange: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "openYTVault(address,address,uint256,int256,uint256,uint256,int128,int128)"(
      _FCPsupplied: string,
      _FCPborrowed: string,
      _yieldSupplied: BigNumberish,
      _bondSupplied: BigNumberish,
      _amountBorrowed: BigNumberish,
      _priceMultiplier: BigNumberish,
      _suppliedRateChange: BigNumberish,
      _borrowRateChange: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
